categories: 
- Assembly
description: fast de novo sequence assembler for long noisy reads
homepage_url: https://github.com/ruanjue/wtdbg2
long_description: |
    Fast long read assembler designed for large genome assembly. 
    Due to it's speed, is a good option for eukaryotic assembly including human.
    
    Wtdbg2 consumes a few hundred gigabytes RAM during an average human assembly, and as large genomes are the intended use-case, a high-memory node 
    is recommended to best serve users. 

    See https://www.nature.com/articles/s41592-019-0669-3 for more information

name: wtdbg2
owner: galaxy-australia
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/wtdbg2
type: unrestricted